# development, staging, production
environment: development

server:
    fqdn: yourdomain.com
    protocol: https
    ports:
        passive: 7080

postgres:
    host: 127.0.0.1
    port: 5432
    database: greatape
    username: postgres
    password: password
