environment: development

server:
    fqdn: localhost
    protocol: http
    ports:
        passive: 7080
    
    # used for secure cookie
    # doc: https://pkg.go.dev/github.com/gorilla/securecookie@v1.1.1
    hash_key: '---INSERT-YOUR-HASH-KEY---'
    block_key: '---INSERT-YOUR-BLOCK-KEY---'

postgres:
    host: 127.0.0.1
    port: 5432
    database: greatape
    username: postgres
    password: password
