environment: development
server:
    protocol: http
    fqdn: localhost
    hash_key: 'OKq2gLmDCYJXnPweKrM=l7dFCDxp5Ff5EupcQCU'
    block_key: 'v1K1s+S3vWudrypR'
mysql:
    database: greatape
    username: root
    password: password
