name: server

on:
  push:
    branches:
      - master

env:
  PORT: 8080

jobs:
  Build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        working-directory: greataped/app
        run: go build -v ./...

      - name: Test
        working-directory: greataped/tests
        run: go test -v ./...
